version: '3.3'
services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: hibernate
      # So you don't have to use root, but you can if you like
      MYSQL_USER: root
      # You can use whatever password you like
      MYSQL_PASSWORD: Admin123
      # Password for root access
      MYSQL_ROOT_PASSWORD: Admin123
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 33060:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  spring-app:
    restart: on-failure
    build: ./
    expose:
     - 8080
    ports:
      - 9000:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql